'use strict';
/*
 * LE VOCABULAIRE DU SITE, EN ANGLAIS — POUR L'AFFICHAGE SEULEMENT
 * =============================================================================
 * Relevé le 2026-09-25 : en anglais, les fenêtres montraient en français tout
 * ce que le SITE leur envoie déjà mis en mots — statuts des commandes, des
 * factures, des retours, des cartes-cadeaux, des conversations, filtres et
 * traitements de la photothèque. Les dictionnaires de src/langue/ ne pouvaient
 * rien y faire : ils traduisent le texte ÉCRIT dans une fenêtre, à la
 * génération, pas une donnée reçue ensuite.
 *
 * ➡ CETTE TABLE, AVEC szTd() DU SOCLE, TRADUIT À L'AFFICHAGE, ET À L'AFFICHAGE
 *   SEULEMENT. La fenêtre reçoit « Payée », l'affiche « Paid » ; ce qui repart au
 *   site reste le CODE (paid), jamais ce texte. C'est sa consigne du 2026-09-12 :
 *   « la traduction doit affecter que la lecture et non pas les données
 *   enregistrées ».
 * ⚠ UN LIBELLÉ ABSENT RESTE EN FRANÇAIS : jamais un trou, jamais une clé brute.
 *   Un statut ajouté demain au site s'affichera en français tant qu'il n'est pas
 *   ici — ce qui se voit, et se corrige d'une ligne.
 * ⚠ LES CLÉS SONT LES LIBELLÉS DU SITE, MOT POUR MOT. Leurs sources, pour les
 *   relire quand elles changent :
 *     admin.js      ORDER_STATUS, _RET_LIBELLES, statuts de facture
 *     pont.js       _FACT_LIBELLES
 *     livechat.js   _STATUS
 *     promo.js      LIB (cartes-cadeaux)
 *     photos.js     EXPL_FILTRES, _TRAITEMENTS
 *     photoroom-proxy.php  les ambiances du Studio (label, desc)
 *     staff.js      ROLES[…].label (les roles du personnel), addLog (actions fixes)
 *     data.js       _HP_DEFAULTS (noms des blocs de l accueil)
 *     admin.js      _HP_DESC, _hsGrad, _ADM_THEMES, _STORE_THEMES,
 *                   _AUTOMATION_JOBS, _STATS_METRICS, _EMAIL_FUNCTIONS,
 *                   SECINC_STEPS (options), _VIEW_META
 *     newsletter.js BDEF (types de blocs)
 *     expenses.js   PAY_METHODS
 *     printagent.js KINDS, PRINT_KINDS
 *     promoprint.js TYPE_LBL, formats standard
 *     social.js     TRIGGERS, VARIABLES
 * ⚠ LE JEU D ESSAI DES BANCS (tools/reponses-fenetres.js) N EST PAS UNE SOURCE.
 *   Il invente parfois ses propres libelles (« Diaporama héro », « Fermée »,
 *   « Expédiée »…) que le site n envoie jamais : on ne les met PAS ici.
 */
module.exports = {
  /* Categories de la boutique (admin.js CAT_LABELS, _NAV_CAT_LABELS ; DB.getInvCats) —
     elles arrivent en `categorie: "Hauts & Blouses"` dans Codes-barres, Produits,
     Liquidation et Collection. Sa capture du 2026-10-02 (Codes-barres en anglais).
     Memes mots que src/langue/libelles.js. */
  'Robes': 'Dresses',
  'Hauts & Blouses': 'Tops & Blouses',
  'Pantalons & Jeans': 'Trousers & Jeans',
  'Pantalons': 'Trousers',
  'Jupes': 'Skirts',
  'Manteaux & Vestes': 'Coats & Jackets',
  'Chaussures': 'Shoes',
  'Accessoires': 'Accessories',
  /* Reseaux sociaux — configuration des jetons (social.js, _SOC_CLES), 2026-09-29 */
  'Jeton de longue durée (Page Access Token) — Meta for Developers → Graph API Explorer.': 'Long-lived token (Page Access Token) — Meta for Developers → Graph API Explorer.',
  'Jeton Instagram Business — même application Meta, avec l’API Instagram Graph activée.': 'Instagram Business token — same Meta app, with the Instagram Graph API enabled.',
  'Jeton Pinterest v5 — developers.pinterest.com → Mon application.': 'Pinterest v5 token — developers.pinterest.com → My app.',
  'Jeton TikTok for Business — developers.tiktok.com (validation de l’application requise).': 'TikTok for Business token — developers.tiktok.com (app review required).',
  'Identifiant de la Page': 'Page ID',
  'Identifiant du compte professionnel': 'Business account ID',
  'Identifiant du tableau': 'Board ID',
  /* Journaux — groupes de la recherche (staff.js, journaux:recherche), 2026-09-29 */
  '🔐 Accès': '🔐 Access',
  '🖨 Impressions': '🖨 Prints',
  '🤖 Automatisations': '🤖 Automations',
  '🔎 Recherches sans résultat': '🔎 Searches with no result',
  /* Caisse (pont.js, caisse:contexte — paiements et remises), 2026-09-29 */
  'Terminal Square (reçu)': 'Square terminal (receipt)',
  'Comptant (reçu)': 'Cash (receipt)',
  'Interac (reçu)': 'Interac (receipt)',
  'Autre (reçu)': 'Other (receipt)',
  'Lien de paiement (téléphone)': 'Payment link (phone)',
  '✉ Envoyer par courriel': '✉ Send by email',
  '🖨 Imprimer seulement': '🖨 Print only',
  '✉ + 🖨 Courriel et impression': '✉ + 🖨 Email and print',
  'Ne rien faire': 'Do nothing',
  // Commandes (ORDER_STATUS)
  'En attente': 'Pending',
  'Confirmée': 'Confirmed',
  'En préparation': 'Preparing',
  'Vérification': 'Verification',
  'En livraison': 'Out for delivery',
  'Livrée': 'Delivered',
  'Annulée': 'Cancelled',
  // Factures (_FACT_LIBELLES)
  'Non payée': 'Unpaid',
  'Payée': 'Paid',
  'En retard': 'Overdue',
  // Retours (_RET_LIBELLES)
  'Photo requise': 'Photo required',
  'Approuvée': 'Approved',
  'Rejetée': 'Rejected',
  'En transit': 'In transit',
  'Reçu — en traitement': 'Received — processing',
  'Remboursée': 'Refunded',
  'Complétée': 'Completed',
  'En attente d’analyse': 'Under review',
  // Conversations (livechat _STATUS)
  'Ouvert': 'Open',
  'Fermé': 'Closed',
  // Cartes-cadeaux (promo LIB)
  'Utilisée': 'Used',
  'Expirée': 'Expired',
  'Activation requise': 'Activation required',
  // Photothèque : filtres (EXPL_FILTRES) et traitements (_TRAITEMENTS)
  'A déjà reçu un traitement': 'Already processed',
  'Jamais traitée': 'Never processed',
  'Détourée (fond transparent)': 'Cut out (transparent background)',
  'Fond d’origine': 'Original background',
  'Rattachée à un produit': 'Linked to a product',
  'Aucun produit': 'No product',
  'Téléversement en cours': 'Uploading',
  'Détourage': 'Background removal',
  'Mannequin retiré': 'Mannequin removed',
  'Porté par un mannequin': 'Worn by a model',
  'Filigrane / logo': 'Watermark / logo',
  // Studio : les ambiances du relais (photoroom-proxy.php, label et desc)
  'Studio épuré': 'Clean studio',
  'Fond neutre, lumière douce — l’article seul, net.': 'Neutral backdrop, soft light — the item alone, crisp.',
  'Plage dorée': 'Golden beach',
  'Sable, mer, lumière dorée de fin de journée.': 'Sand, sea, golden late-day light.',
  'Béton chic': 'Chic concrete',
  'Béton clair, urbain minimal, ombre franche.': 'Light concrete, minimal urban, crisp shadow.',
  'Verdure': 'Greenery',
  'Végétation, lumière naturelle, frais et aéré.': 'Plants, natural light, fresh and airy.',
  'Nuit lumières': 'City lights',
  'Lumières de ville floutées, ambiance éditoriale.': 'Blurred city lights, editorial mood.',
  // Roles du personnel (staff.js, ROLES[…].label) — affiches par Personnel connecte
  'Super-administrateur': 'Super administrator',
  'Administrateur': 'Administrator',
  'Gérant de boutique': 'Store manager',
  'Comptable': 'Accountant',
  'Commis à la livraison': 'Shipping clerk',
  'Commis à la préparation de commandes': 'Order picking clerk',
  'Commis à l’inventaire': 'Inventory clerk',
  'Service à la clientèle': 'Customer service',
  'Marketing': 'Marketing',
  'Consultation seulement': 'Read-only',
  // Page d accueil : noms des blocs (data.js, _HP_DEFAULTS[…].label) — op config:accueil:donnees
  'Bannière héros': 'Hero banner',
  'Grille catégories': 'Category grid',
  'Coups de cœur': 'Favourites',
  'Collections': 'Collections',
  'Bannière livraison': 'Shipping banner',
  // Page d accueil : descriptions des blocs (admin.js, _HP_DESC) et degrades des diapos (_hsGrad[…].label) — op config:accueil:donnees
  'Diaporama plein écran avec transitions': 'Full-screen slideshow with transitions',
  'Grille des catégories': 'Category grid',
  'Produits mis en avant': 'Featured products',
  'Cartes des collections actives': 'Active collection cards',
  'Bannière bas de page avec CTA': 'Footer banner with call to action',
  'Nuit bleue': 'Blue night',
  'Violet royal': 'Royal purple',
  'Forêt sombre': 'Dark forest',
  'Bordeaux': 'Burgundy',
  'Charbon doré': 'Golden charcoal',
  'Encre marine': 'Navy ink',
  // Apparence : noms des themes (admin.js, _ADM_THEMES et _STORE_THEMES[…].label) — op config:apparence:donnees
  'Défaut': 'Default',
  'Océan': 'Ocean',
  'Violet': 'Violet',
  'Ardoise': 'Slate',
  'Graphite': 'Graphite',
  'Émeraude': 'Emerald',
  'Forêt': 'Forest',
  'Moderne': 'Modern',
  'Rose': 'Rose',
  'Or': 'Gold',
  // Automatisations : les taches planifiees (admin.js, _AUTOMATION_JOBS : name, schedule, desc, recommendation) et les metriques du resume (_STATS_METRICS[…].label) — op config:automations:donnees
  "Réveil de l'hébergement": 'Hosting wake-up',
  'Toutes les 10 minutes': 'Every 10 minutes',
  "Garde le serveur et la connexion à la base éveillés, pour qu'aucun client n'attende un réveil — surtout au retour d'un paiement.": 'Keeps the server and the database connection awake, so that no customer waits for a wake-up — especially when coming back from a payment.',
  "Toutes les 10 minutes (Render s'endort après environ 15 minutes sans visite). N'écrit rien, n'envoie aucun courriel : une requête SELECT 1 et c'est tout.": 'Every 10 minutes (Render goes to sleep after about 15 minutes without a visit). Writes nothing, sends no email: one SELECT 1 query and that is all.',
  'Statistiques quotidiennes': 'Daily statistics',
  'Une fois par jour': 'Once a day',
  "Commandes d'hier, revenu brut, variantes à réapprovisionner et retours en attente.": 'Yesterday’s orders, gross revenue, variants to restock and pending returns.',
  'Une fois par jour, idéalement en soirée pour couvrir toute la journée précédente.': 'Once a day, ideally in the evening to cover the whole previous day.',
  'Expiration des mots de passe': 'Password expiry',
  "Avertit chaque membre du personnel quelques jours avant l'expiration de son mot de passe.": 'Warns each staff member a few days before their password expires.',
  'Une fois par jour.': 'Once a day.',
  'Rappel de coupon expirant': 'Expiring coupon reminder',
  "Prévient un client 3 jours avant l'expiration d'un coupon de récompense fidélité.": 'Notifies a customer 3 days before a loyalty reward coupon expires.',
  'Suivi de livraison automatique': 'Automatic delivery tracking',
  'Aux 30 minutes': 'Every 30 minutes',
  "Vérifie le statut auprès du transporteur et confirme la livraison au client dès qu'elle est détectée.": 'Checks the status with the carrier and confirms delivery to the customer as soon as it is detected.',
  'Aux 30 minutes, pour détecter rapidement une livraison confirmée par le transporteur.': 'Every 30 minutes, to quickly detect a delivery confirmed by the carrier.',
  'Chaînes automatisées infolettre': 'Automated newsletter chains',
  'Aux heures': 'Hourly',
  'Traite les étapes dues des séquences infolettre (voir Newsletter → Automatisation).': 'Processes the due steps of the newsletter sequences (see Newsletter → Automation).',
  "Aux heures (toutes les heures). ⚠️ Si des inscriptions se sont accumulées sans jamais avoir été traitées, le premier passage enverra tout d'un coup — faites un test manuel et vérifiez le résultat avant d'activer l'horaire régulier.": 'Hourly (every hour). ⚠️ If sign-ups have piled up without ever being processed, the first run will send everything at once — run a manual test and check the result before turning on the regular schedule.',
  'Publication réseaux sociaux': 'Social media publishing',
  'Publie automatiquement les entrées en attente de la file des réseaux sociaux.': 'Automatically publishes the pending entries of the social media queue.',
  'Entretien': 'Maintenance',
  "Purge l'archive des retours et les sessions expirées.": 'Purges the returns archive and expired sessions.',
  'Une fois par jour, idéalement la nuit (ex. 3h du matin, faible trafic).': 'Once a day, ideally at night (e.g. 3 a.m., low traffic).',
  'Vérification des taux de taxe': 'Tax rate check',
  "Compare chaque taux enregistré au taux officiel et avertit par courriel dès qu'un taux diverge, qu'une province manque ou qu'une ligne de taxe est en trop. Rappelle aussi de réviser les taux au-delà de 90 jours.": 'Compares each saved rate with the official rate and warns by email as soon as a rate differs, a province is missing or a tax line is extra. Also reminds you to review the rates after 90 days.',
  "Une fois par jour. Rien n'est envoyé quand tout concorde : un courriel signifie qu'un taux mérite un coup d'œil.": 'Once a day. Nothing is sent when everything matches: an email means a rate deserves a look.',
  'Commandes': 'Orders',
  'Revenu brut': 'Gross revenue',
  'Ventes nettes (revenu − remboursements)': 'Net sales (revenue − refunds)',
  'Panier moyen': 'Average order',
  'Articles vendus': 'Items sold',
  'Taxes perçues': 'Taxes collected',
  'Livraison encaissée': 'Shipping collected',
  'Rabais accordés (coupons)': 'Discounts given (coupons)',
  'Remboursements effectués': 'Refunds issued',
  'Crédits boutique émis': 'Store credits issued',
  'Commandes à préparer (à ce jour)': 'Orders to prepare (to date)',
  'Nouveaux clients': 'New customers',
  'Nouveaux abonnés infolettre': 'New newsletter subscribers',
  'Désabonnements infolettre': 'Newsletter unsubscribes',
  'Publications réseaux sociaux': 'Social media posts',
  'Variantes à réapprovisionner (sous leur seuil)': 'Variants to restock (below their threshold)',
  'Retours nécessitant attention': 'Returns needing attention',
  // Campagnes : types de blocs du courriel (newsletter.js, BDEF[…].label) — op nl:blocsCatalogue
  'Titre': 'Heading',
  'Texte': 'Text',
  'Bouton': 'Button',
  'Séparateur': 'Divider',
  'Espacement': 'Spacer',
  'Encadré code': 'Code box',
  'Bannière réduction': 'Discount banner',
  'Encadré info': 'Info box',
  'HTML libre': 'Custom HTML',
  // Depenses : modes de paiement (expenses.js, PAY_METHODS[…].label) — op depenses:donnees
  'Carte de crédit / débit': 'Credit / debit card',
  'Comptant': 'Cash',
  'Virement / prélèvement': 'Transfer / direct debit',
  'Chèque': 'Cheque',
  'Autre': 'Other',
  // Gabarits courriel : fonctions et modules (admin.js, _EMAIL_FUNCTIONS : label, module) — op config:gabarits:donnees
  '🛒 Confirmation de commande': '🛒 Order confirmation',
  "🚚 Avis d'expédition": '🚚 Shipping notice',
  '📦 Retours (toutes étapes)': '📦 Returns (all steps)',
  '🔔 Retour en inventaire': '🔔 Back in stock',
  '💳 Carte-cadeau': '💳 Gift card',
  '🏷️ Code promotionnel envoyé client': '🏷️ Promo code sent to customer',
  '🔑 Réinitialisation mot de passe': '🔑 Password reset',
  '📧 Campagnes infolettre': '📧 Newsletter campaigns',
  '🔗 Chaînes automatisées': '🔗 Automated chains',
  '🎁 Code de bienvenue (infolettre)': '🎁 Welcome code (newsletter)',
  '💬 Chat hors-ligne / contact': '💬 Offline chat / contact',
  '📧 Bienvenue / Mot de passe temporaire': '📧 Welcome / Temporary password',
  '⚠ Avertissement inactivité (staff)': '⚠ Inactivity warning (staff)',
  '⚠ Avertissement inactivité (clients)': '⚠ Inactivity warning (customers)',
  '📋 Sondage / satisfaction': '📋 Survey / satisfaction',
  '📊 Lien comptable (accès comptable)': '📊 Accountant link (accountant access)',
  '📊 Résumé quotidien': '📊 Daily summary',
  '📦 Confirmation de livraison': '📦 Delivery confirmation',
  '🎁 Rappel de coupon expirant': '🎁 Expiring coupon reminder',
  '🔑 Expiration mot de passe (personnel)': '🔑 Password expiry (staff)',
  'Panier': 'Cart',
  'Expédition': 'Shipping',
  'Retours': 'Returns',
  'Inventaire': 'Inventory',
  'Promotions': 'Promotions',
  'Compte': 'Account',
  'Newsletter': 'Newsletter',
  'Chat': 'Chat',
  'Personnel': 'Staff',
  'Clients': 'Customers',
  'Fidélisation': 'Loyalty',
  'Comptabilité': 'Accounting',
  'Automatisations': 'Automations',
  // Imprimantes : les usages (printagent.js, KINDS[…].label) — op imprimantes:etat ; types de documents du journal d impression (PRINT_KINDS) — op journal:donnees
  'Codes-barres': 'Barcodes',
  "Étiquettes d'expédition": 'Shipping labels',
  'Factures (8,5 × 11 po)': 'Invoices (8.5 × 11 in)',
  'Bon de commande': 'Purchase order',
  'Bordereau de préparation': 'Packing slip',
  "Étiquette d'expédition": 'Shipping label',
  'Étiquette code-barres': 'Barcode label',
  'Objet promotionnel': 'Promotional item',
  'Facture': 'Invoice',
  'Rapport': 'Report',
  "Test d'impression": 'Test print',
  'Autre document': 'Other document',
  // Incidents de confidentialite : types, avis CAI et options du formulaire (admin.js, SECINC_STEPS options ; colonne cai des lignes) — op incidents:donnees
  'Perte de renseignements': 'Loss of information',
  'Vol': 'Theft',
  'Accès non autorisé': 'Unauthorized access',
  'Communication non autorisée': 'Unauthorized disclosure',
  'Destruction / altération': 'Destruction / alteration',
  'Rançongiciel / logiciel malveillant': 'Ransomware / malware',
  'Hameçonnage': 'Phishing',
  'Erreur d’envoi / de manipulation': 'Sending / handling error',
  'Non requis': 'Not required',
  'Oui, transmis': 'Yes, sent',
  'À faire': 'To do',
  'Non': 'No',
  'Oui': 'Yes',
  'En cours d’évaluation': 'Being assessed',
  'Ouvert / en cours': 'Open / in progress',
  'Sous surveillance': 'Under watch',
  'Clôturé': 'Closed',
  // Journal d acces : actions ecrites telles quelles par le site (staff.js, addLog(type, action) sans partie variable) — op journal:donnees. ⚠ Les actions qui portent un nom, un numero ou un courriel restent en francais : ce sont des phrases composees.
  'Connexion réussie': 'Successful sign-in',
  'Connexion MFA réussie': 'Successful MFA sign-in',
  'Connexion + MFA configuré': 'Sign-in + MFA set up',
  'Code MFA invalide': 'Invalid MFA code',
  'Délai MFA dépassé (60 s) — session effacée': 'MFA timed out (60 s) — session cleared',
  'Compte désactivé': 'Account disabled',
  'Compte désactivé automatiquement pour inactivité': 'Account automatically disabled for inactivity',
  'Compte réactivé via lien courriel': 'Account reactivated via email link',
  'Déconnexion': 'Sign-out',
  'Mot de passe changé à la 1re connexion': 'Password changed at first sign-in',
  'Mot de passe changé à la 1ʳᵉ connexion': 'Password changed at first sign-in',
  'Mot de passe renouvelé (expiration)': 'Password renewed (expiry)',
  'Questions de sécurité configurées à la 1re connexion': 'Security questions set up at first sign-in',
  'Questions de sécurité configurées à la 1ʳᵉ connexion': 'Security questions set up at first sign-in',
  // Modeles (mannequins par vue) : les vues (admin.js, _VIEW_META[…].label) — op config:modeles:donnees
  'Face': 'Front',
  'Derrière': 'Back',
  'Gauche': 'Left',
  'Droit': 'Right',
  // Impression promotionnelle : types et formats standard (promoprint.js, TYPE_LBL et formats[…].name) — op promo:donnees. ⚠ Le nom d un format PERSONNALISE n est pas passe par ici.
  "Carte d'affaires": 'Business card',
  'Étiquette': 'Label',
  'Autocollant': 'Sticker',
  'Autocollant carré': 'Square sticker',
  'Autocollant rond': 'Round sticker',
  'Étiquette prix': 'Price tag',
  // Reseaux sociaux : declencheurs et variables des patrons (social.js, TRIGGERS et VARIABLES) — op patrons:liste
  '🆕 Nouveau produit ajouté': '🆕 New product added',
  '📦 Nouvelle collection créée': '📦 New collection created',
  '🏷 Nouvelle promotion activée': '🏷 New promotion activated',
  '✋ Publication manuelle': '✋ Manual post',
  '⏰ Publication planifiée': '⏰ Scheduled post',
  'Nom du produit': 'Product name',
  'Prix': 'Price',
  'Catégorie': 'Category',
  'Nom de la collection': 'Collection name',
  'Code promo': 'Promo code',
  '% de réduction': '% off',
  'Nom de la boutique': 'Store name',
  'URL de la boutique': 'Store URL',
  'Hashtags': 'Hashtags',
  // Registre des deplacements (vehicules.js, TYPES[…].nom et RAISONS[…].nom) — ops vehicules:donnees
  // et depenses:donnees (typesVehicule). Les memes mots que la colonne `en` du site.
  // ⚠ Lecture seule : ce qui repart au site est la CLE (essence, fournisseur…), jamais ce nom.
  'Essence / recharge': 'Fuel / charging',
  'Entretien (huile, pneus, lavage)': 'Maintenance (oil, tires, washing)',
  'Réparations': 'Repairs',
  'Assurance': 'Insurance',
  'Immatriculation et permis': 'Registration and licence',
  'Intérêts sur le prêt auto': 'Car loan interest',
  'Location (crédit-bail)': 'Leasing',
  'Stationnement (affaires)': 'Parking (business)',
  'Péages (affaires)': 'Tolls (business)',
  'Autre frais de véhicule': 'Other vehicle expense',
  'Visite fournisseur': 'Supplier visit',
  'Livraison à un client': 'Customer delivery',
  'Bureau de poste / transporteur': 'Post office / carrier',
  'Achats pour l’entreprise': 'Business purchases',
  'Banque': 'Bank',
  'Salon, marché, événement': 'Fair, market, event',
  'Séance photo': 'Photo shoot',
  'Rencontre client': 'Client meeting',
  'Autre raison d’affaires': 'Other business purpose',
  // Les regles de premiere annee de la DPA (vehicules.js, dpaCoeur, `regle`) — op vehicules:donnees.
  // IIA = incitatif a l investissement accelere = AII (Accelerated Investment Incentive).
  'IIA 100 %': 'AII 100%',
  'IIA 75 %': 'AII 75%',
  'IIA 55 %': 'AII 55%',
  'demi-année': 'half-year rule',
  'IIA × 1,5': 'AII × 1.5',
  'sans demi-année': 'no half-year rule',
  '30 %': '30%',
  'vente': 'sale',
  'vente 10.1 (½)': 'sale, class 10.1 (½)',
  // Rappels (rappels.js : FREQUENCES[…].nom, MODULES[…].nom, MODELES[…].titre et .note) — op rappels:donnees.
  // ⚠ Lecture seule : ce qui repart au site est la CLE (mensuel, depenses, acomptes…), jamais ce texte.
  // « Inventaire » et « Commandes » sont deja plus haut.
  'Une seule fois': 'Once',
  'Chaque jour': 'Every day',
  'Chaque semaine': 'Every week',
  'Chaque mois': 'Every month',
  'Chaque trimestre': 'Every quarter',
  'Chaque année': 'Every year',
  '— aucun —': '— none —',
  'Dépenses': 'Expenses',
  'Véhicules et déplacements': 'Vehicles and mileage',
  'Fiscalité et impôt': 'Tax',
  'Conciliation bancaire': 'Bank reconciliation',
  'Livre de comptes': 'General ledger',
  'Rapports et budget': 'Reports and budget',
  'Factures': 'Invoices',
  'Saisir les dépenses de la semaine': 'Enter this week’s expenses',
  'Factures, reçus, relevés : une dépense saisie tout de suite garde sa pièce et ses taxes.':
    'Invoices, receipts, statements: an expense entered right away keeps its receipt and its taxes.',
  'Inscrire les déplacements de la semaine': 'Log this week’s trips',
  'Le registre fait la part d’affaires du véhicule : un déplacement oublié est une déduction perdue.':
    'The logbook sets the vehicle’s business share: a forgotten trip is a lost deduction.',
  'Conciliation bancaire du mois': 'Monthly bank reconciliation',
  'Rapprocher le relevé du mois précédent.': 'Reconcile the previous month’s statement.',
  'Remise TPS/TVQ du trimestre': 'Quarterly GST/QST remittance',
  'Déclaration et paiement un mois après la fin du trimestre (30 avril, 31 juillet, 31 octobre, 31 janvier). Lignes 106 et 206 : les CTI/RTI des dépenses.':
    'Return and payment one month after the end of the quarter (April 30, July 31, October 31, January 31). Lines 106 and 206: the ITCs/ITRs on expenses.',
  'Acompte provisionnel (impôt fédéral et du Québec)': 'Tax instalment (federal and Quebec)',
  '15 mars, 15 juin, 15 septembre, 15 décembre.': 'March 15, June 15, September 15, December 15.',
  'Relever l’odomètre de chaque véhicule': 'Read each vehicle’s odometer',
  'Le compteur au 31 décembre ferme l’année et ouvre la suivante : sans lui, la part d’affaires n’est pas établie.':
    'The odometer on December 31 closes the year and opens the next: without it, the business share is not established.',
  'Payer le solde d’impôt de l’année': 'Pay the year’s balance of tax',
  'Le solde est dû le 30 avril, même si la déclaration d’un travailleur autonome peut attendre au 15 juin.':
    'The balance is due April 30, even though a self-employed person’s return can wait until June 15.',
  'Déposer la déclaration de revenus (T1 et TP-1)': 'File the income tax return (T1 and TP-1)',
  'Travailleur autonome : au plus tard le 15 juin. Imprimez la T2125 et le TP-80 depuis Fiscalité et impôt.':
    'Self-employed: by June 15 at the latest. Print the T2125 and the TP-80 from Tax.',
};
